# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 12:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Certificate_Type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificate_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_name', models.CharField(max_length=200)),
                ('instructor_name', models.CharField(max_length=250)),
                ('director_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Course_Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course_template', models.FileField(upload_to='course_certificate_templates')),
                ('course_certificate_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.Certificate_Type')),
                ('course_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('student_email', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_name', models.CharField(max_length=200)),
                ('workshop_instructor_name', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Workshop_Certificate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workshop_template', models.FileField(upload_to='workshop_certificate_templates')),
                ('workshop_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.Workshop')),
            ],
        ),
    ]
