# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 04:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course_Certificate_Type',
            fields=[
                ('certificate_type_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='certificate.Certificate_Type')),
                ('certificate_for', models.CharField(max_length=255)),
            ],
            bases=('certificate.certificate_type',),
        ),
    ]
