# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 04:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0002_course_certificate_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_certificate',
            name='course_certificate_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='certificate.Course_Certificate_Type'),
        ),
    ]
