# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-19 04:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('certificate', '0003_auto_20180519_0953'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course_certificate',
            name='course_name',
        ),
    ]
